# Generated by Django 5.1.6 on 2025-03-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='syllabus_file',
            field=models.FileField(blank=True, null=True, upload_to='syllabus/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='syllabus_file',
            field=models.FileField(blank=True, null=True, upload_to='syllabus/'),
        ),
    ]
