# Generated by Django 4.2.20 on 2025-03-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0004_category_syllabus_file_subcategory_syllabus_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='eligibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='marking_scheme',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='official_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('jee', 'JEE Main'), ('gate', 'GATE'), ('neet', 'NEET'), ('aiims', 'AIIMS'), ('ssc', 'SSC'), ('upsc', 'UPSC'), ('ibps', 'IBPS'), ('sbi-po', 'SBI PO')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='subjects',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('medical', 'Medical'), ('government', 'Government'), ('banking', 'Banking')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
